# Generated by Django 4.0 on 2022-12-06 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import waddensea.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to=waddensea.models.entity_image_path)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Регион')),
                ('short_desc', models.TextField(verbose_name='Краткое описание')),
                ('desc', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to=waddensea.models.entity_image_path)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('latin_name', models.CharField(max_length=150, verbose_name='Латинское название')),
                ('short_desc', models.TextField(verbose_name='Краткое описание')),
                ('desc', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to=waddensea.models.base_image_path)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('publication_date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waddensea.category', verbose_name='Категория')),
                ('region', models.ManyToManyField(blank=True, to='waddensea.Region', verbose_name='Регион')),
            ],
        ),
    ]
